#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Oct 18, 2023 04:18:14 PM -03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1200x590+120+61
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1041
    wm minsize $top 166 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "MDIA - Metallographic Image Analyzer"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m43" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    
set site_3_0 $top.m43
    $top.m43 add cascade \
        -menu "$top.m43.men44" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "{}" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "File" 
    menu "$site_3_0.men44" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground black -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men44 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#load_file" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Load Image" 
    $site_3_0.men44 add separator \
        -background $vTcl(actual_gui_bg) 
    $site_3_0.men44 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#quit_app" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Quit" 
    
set site_3_0 $top.m43
    $top.m43 add cascade \
        -menu "$top.m43.men46" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "{}" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Segmentation" 
    menu "$site_3_0.men46" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground black -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men46 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#find_grains" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Grains" 
    $site_3_0.men46 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "{}" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Phases" 
    $site_3_0.men46 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#grains_histogram" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Grains histogram" 
    
set site_3_0 $top.m43
    $top.m43 add cascade \
        -menu "$top.m43.men48" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "{}" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Tools" 
    menu "$site_3_0.men48" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground black -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#open_algorithm_window" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) \
        -label "Image Segmentation Manager" 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#draw_histogram" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Gray Image Histogram" 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#show_filtered_image" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Show filtered image" 
    
set site_3_0 $top.m43
    $top.m43 add cascade \
        -menu "$top.m43.men47" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "{}" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "Help" 
    menu "$site_3_0.men47" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground black -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men47 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command "#about" -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -label "About" 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$top.tNo43" \
        -width 1248 -height 680 -takefocus {} 
    vTcl:DefineAlias "$top.tNo43" "TNB_main" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    frame "$top.tNo43.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t0" "TNB_main_t0" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    $top.tNo43 add $top.tNo43.t0 \
        -padding 0 -sticky nsew -state normal -text "Image Analysis" \
        -image {} -compound left -underline -1 
    set site_4_0  $top.tNo43.t0
    frame "$site_4_0.fra45" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 680 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1190 
    vTcl:DefineAlias "$site_4_0.fra45" "Frame1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_0.fra45
    canvas "$site_5_0.can49" \
        -background #cddcdc -borderwidth 2 -closeenough 1.0 -height 630 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #c4c4c4 \
        -selectforeground black -width 930 
    vTcl:DefineAlias "$site_5_0.can49" "Canvas1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    labelframe "$site_5_0.lab52" \
        -font "TkDefaultFont" -foreground black \
        -text "Metallographic procedures" -background $vTcl(actual_gui_bg) \
        -height 235 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 230 
    vTcl:DefineAlias "$site_5_0.lab52" "Labelframe2" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_6_0 $site_5_0.lab52
    radiobutton "$site_6_0.rad54" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Jeffries" -value "0" -variable "RB_var_MP" 
    vTcl:DefineAlias "$site_6_0.rad54" "RB_Procedure_Planimetric" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    bind $site_6_0.rad54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {It involves 
an actual count of the number of grains within a known
area. The number of grains per unit area, NA , is used to
determine the ASTM grain size number, G.}
    }
    vTcl:copy_lock $site_6_0.rad54
    button "$site_6_0.but61" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command "metallographic_procedures" \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "OK" 
    vTcl:DefineAlias "$site_6_0.but61" "Button1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    radiobutton "$site_6_0.rad43" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Heyn" -value "1" -variable "RB_var_MP" 
    vTcl:DefineAlias "$site_6_0.rad43" "Radiobutton5" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    bind $site_6_0.rad43 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Estimate the average grain size by counting the number of grains intercepted by one ormore straight lines sufficiently long to yield at least 50 intercepts.}
    }
    vTcl:copy_lock $site_6_0.rad43
    radiobutton "$site_6_0.rad44" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Hilliard Single-Circle" -value "2" \
        -variable "RB_var_MP" 
    vTcl:DefineAlias "$site_6_0.rad44" "Radiobutton6" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_6_0.rad44
    radiobutton "$site_6_0.rad46" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Abrams Three-Circle" -value "3" \
        -variable "RB_var_MP" 
    vTcl:DefineAlias "$site_6_0.rad46" "Radiobutton2" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_6_0.rad46
    spinbox "$site_6_0.spi43" \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -to 10.0 
    vTcl:DefineAlias "$site_6_0.spi43" "Spinbox_number_lines" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    label "$site_6_0.lab44" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Number of lines" 
    vTcl:DefineAlias "$site_6_0.lab44" "Label1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    label "$site_6_0.lab45" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Lines length" 
    vTcl:DefineAlias "$site_6_0.lab45" "Label2" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    entry "$site_6_0.ent47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_6_0.ent47" "Entry_line_length" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    label "$site_6_0.lab48" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "mm" 
    vTcl:DefineAlias "$site_6_0.lab48" "Label3" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    checkbutton "$site_6_0.che49" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Free orientation" \
        -variable "chkbtn_free_orientation" 
    vTcl:DefineAlias "$site_6_0.che49" "CheckBtn_free_orientation" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    bind $site_6_0.che49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Click on image to trace straight lines with random orientation}
    }
    place $site_6_0.rad54 \
        -in $site_6_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_6_0.but61 \
        -in $site_6_0 -x 90 -y 190 -width 50 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.rad43 \
        -in $site_6_0 -x 10 -y 45 -anchor nw -bordermode ignore 
    place $site_6_0.rad44 \
        -in $site_6_0 -x 10 -y 139 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.rad46 \
        -in $site_6_0 -x 10 -y 161 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.spi43 \
        -in $site_6_0 -x 140 -y 67 -width 30 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab44 \
        -in $site_6_0 -x 40 -y 67 -width 91 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab45 \
        -in $site_6_0 -x 40 -y 90 -anchor nw -bordermode ignore 
    place $site_6_0.ent47 \
        -in $site_6_0 -x 140 -y 90 -width 30 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab48 \
        -in $site_6_0 -x 170 -y 90 -anchor nw -bordermode ignore 
    place $site_6_0.che49 \
        -in $site_6_0 -x 40 -y 110 -anchor nw -bordermode ignore 
    labelframe "$site_5_0.lab62" \
        -font "TkDefaultFont" -foreground black \
        -text "Image structure segmetation" -background $vTcl(actual_gui_bg) \
        -height 105 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 230 
    vTcl:DefineAlias "$site_5_0.lab62" "Labelframe3" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_6_0 $site_5_0.lab62
    button "$site_6_0.but63" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) \
        -command "image_segmentation_procedure" -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "OK" 
    vTcl:DefineAlias "$site_6_0.but63" "Button2" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    radiobutton "$site_6_0.rad43" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Grains" -value "0" -variable "RB_var_ISS" 
    vTcl:DefineAlias "$site_6_0.rad43" "RB_Grains" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_6_0.rad43
    radiobutton "$site_6_0.rad44" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Phases" -value "1" -variable "RB_var_ISS" 
    vTcl:DefineAlias "$site_6_0.rad44" "RB_Phases" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    checkbutton "$site_6_0.che43" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Fill contours" -variable "fill_contours_chkbox" 
    vTcl:DefineAlias "$site_6_0.che43" "Checkbutton1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    place $site_6_0.but63 \
        -in $site_6_0 -x 90 -y 60 -width 50 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.rad43 \
        -in $site_6_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_6_0.rad44 \
        -in $site_6_0 -x 10 -y 40 -width 64 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.che43 \
        -in $site_6_0 -x 80 -y 20 -width 101 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_5_0.lab43" \
        -font "TkDefaultFont" -foreground black -relief flat \
        -text "Image directory:" -background $vTcl(actual_gui_bg) -height 40 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 930 
    vTcl:DefineAlias "$site_5_0.lab43" "Labelframe1" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_6_0 $site_5_0.lab43
    label "$site_6_0.lab44" \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text "File name path" 
    vTcl:DefineAlias "$site_6_0.lab44" "Label_FNP" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    place $site_6_0.lab44 \
        -in $site_6_0 -x 4 -y 17 -width 894 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_5_0.lab50" \
        -font "TkDefaultFont" -foreground black -text "Image data" \
        -background $vTcl(actual_gui_bg) -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 220 
    vTcl:DefineAlias "$site_5_0.lab50" "Labelframe6" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_6_0 $site_5_0.lab50
    label "$site_6_0.lab51" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Magnification" 
    vTcl:DefineAlias "$site_6_0.lab51" "Label4" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    entry "$site_6_0.ent52" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_6_0.ent52" "Entry_Magnification" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    label "$site_6_0.lab53" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Scale: unknown" 
    vTcl:DefineAlias "$site_6_0.lab53" "Label5" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    bind $site_6_0.lab53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Click on two end points scale to inform length (in) or (mm)}
    }
    label "$site_6_0.lab54" \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "X" 
    vTcl:DefineAlias "$site_6_0.lab54" "Label6" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    button "$site_6_0.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command "image_data_set" \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Get from image" 
    vTcl:DefineAlias "$site_6_0.but56" "Button3" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    radiobutton "$site_6_0.rad57" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "(in)" -value "0" -variable "scale_btn" 
    vTcl:DefineAlias "$site_6_0.rad57" "RBtn_inches" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    radiobutton "$site_6_0.rad58" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "(mm)" -value "1" -variable "scale_btn" 
    vTcl:DefineAlias "$site_6_0.rad58" "RBtn_millimeters" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    place $site_6_0.lab51 \
        -in $site_6_0 -x 0 -relx 0.045 -y 20 -width 80 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_6_0.ent52 \
        -in $site_6_0 -x 100 -y 0 -rely 0.174 -width 40 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab53 \
        -in $site_6_0 -x 0 -relx 0.045 -y 45 -anchor nw -bordermode ignore 
    place $site_6_0.lab54 \
        -in $site_6_0 -x 140 -y 20 -width 13 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_6_0.but56 \
        -in $site_6_0 -x 0 -relx 0.045 -y 0 -rely 0.609 -width 112 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.rad57 \
        -in $site_6_0 -x 0 -relx 0.568 -y 0 -rely 0.609 -width 0 \
        -relwidth 0.173 -height 0 -relheight 0.217 -anchor nw \
        -bordermode ignore 
    place $site_6_0.rad58 \
        -in $site_6_0 -x 0 -relx 0.75 -y 0 -rely 0.609 -width 0 \
        -relwidth 0.218 -height 0 -relheight 0.217 -anchor nw \
        -bordermode ignore 
    button "$site_5_0.but44" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Create Statistics" 
    vTcl:DefineAlias "$site_5_0.but44" "Button_create_stat" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    place $site_5_0.can49 \
        -in $site_5_0 -x 10 -y 10 -width 930 -relwidth 0 -height 630 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab52 \
        -in $site_5_0 -x 0 -relx 0.798 -y 0 -rely 0.377 -width 0 \
        -relwidth 0.192 -height 0 -relheight 0.341 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab62 \
        -in $site_5_0 -x 950 -y 139 -width 230 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab43 \
        -in $site_5_0 -x 0 -relx 0.008 -y 640 -width 930 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 953 -y 10 -width 220 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but44 \
        -in $site_5_0 -x 0 -relx 0.857 -y 0 -rely 0.754 -width 0 \
        -relwidth 0.082 -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.fra45 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 0.995 -height 0 \
        -relheight 0.994 -anchor nw -bordermode ignore 
    frame "$top.tNo43.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t1" "TNB_main_Statistics" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    $top.tNo43 add $top.tNo43.t1 \
        -padding 0 -sticky nsew -state normal -text "Statistics" -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo43.t1
    frame "$site_4_1.fra46" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 630 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1080 
    vTcl:DefineAlias "$site_4_1.fra46" "Frame_Stat" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_1.fra46
    canvas "$site_5_0.can45" \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 463 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #c4c4c4 \
        -selectforeground black -width 672 
    vTcl:DefineAlias "$site_5_0.can45" "Canvas_Stat" vTcl:WidgetProc "MainWindow" 1
### SPOT dump_widget_opt A
    place $site_5_0.can45 \
        -in $site_5_0 -x 0 -relx 0.017 -y 0 -rely 0.031 -width 0 \
        -relwidth 0.566 -height 0 -relheight 0.712 -anchor nw \
        -bordermode ignore 
    place $site_4_1.fra46 \
        -in $site_4_1 -x 5 -y 0 -width 0 -relwidth 0.995 -height 650 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo43 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 720 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top42 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

