#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 10, 2024 08:49:04 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import gui_main_2_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return
    gui_main_2_support.root.tk.eval('set ::xframe #d9d9d9')
    gui_main_2_support.root.tk.eval('set ::xfore #000000')
    gui_main_2_support.root.tk.eval('set ::ana2color beige')
    gui_main_2_support.root.tk.eval('set ::_tabfg1 black')
    gui_main_2_support.root.tk.eval('set ::_tabfg2 white')
    gui_main_2_support.root.tk.eval('set ::_tabbg1 #d9d9d9')
    gui_main_2_support.root.tk.eval('set ::_tabbg2 gray40')
    gui_main_2_support.root.tk.eval('set ::_bgmode light')        
    try: gui_main_2_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'page-legacy.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('page-legacy')
    style.configure('.', font = "TkDefaultFont")
    gui_main_2_support.root.tk_setPalette(
            foreground = '#000000',
            background = '#d9d9d9',
            activeForeground = 'black',
            activeBackground = '#d9d9d9',
            selectForeground = 'black',
            selectBackground =  '#d9d9d9')
    _style_code_ran = 1

class Toplevel_MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1284x680+137+11")
        top.minsize(120, 1)
        top.maxsize(1540, 825)
        top.resizable(1,  1)
        top.title("MEDIA - Metallographic Digital Image Analyzer")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(self.menubar, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='File', menu=self.sub_menu
                ,)
        self.sub_menu.add_command(command=gui_main_2_support.open_image_file
                ,compound='left', label='Open image file')
        self.sub_menu.add_command(command=gui_main_2_support.exporttoxlxs
                ,compound='left', label='Export to Excel')
        self.sub_menu.add_separator()
        self.sub_menu.add_command(command=gui_main_2_support.close_application
                ,compound='left', label='Quit')
        self.sub_menu1 = tk.Menu(self.menubar, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='Image analysis'
                ,menu=self.sub_menu1, )
        self.sub_menu1.add_command(command=gui_main_2_support.open_segmentation_panel
                ,compound='left', label='Segmentation Panel')
        self.sub_menu1.add_command(command=gui_main_2_support.open_procedure_panel
                ,compound='left', label='Measuring procedures')
        self.sub_menu12 = tk.Menu(self.menubar, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='Help'
                ,menu=self.sub_menu12, )
        self.sub_menu12.add_command(compound='left',label='Tutorial')
        self.sub_menu12.add_separator()
        self.sub_menu12.add_command(command=gui_main_2_support.about
                ,compound='left', label='About')

        self.MainFrame = tk.Frame(self.top)
        self.MainFrame.place(relx=0.008, rely=0.015, relheight=0.971
                , relwidth=0.988)
        self.MainFrame.configure(relief='groove')
        self.MainFrame.configure(borderwidth="2")
        self.MainFrame.configure(relief="groove")
        self.MainFrame.configure(background="#d9d9d9")
        self.MainFrame.configure(highlightbackground="#d9d9d9")
        self.MainFrame.configure(highlightcolor="#000000")

        self.MainCanvas = tk.Canvas(self.MainFrame)
        self.MainCanvas.place(relx=0.008, rely=0.015, relheight=0.894
                , relwidth=0.63)
        self.MainCanvas.configure(background="#d9d9d9")
        self.MainCanvas.configure(borderwidth="2")
        self.MainCanvas.configure(highlightbackground="#d9d9d9")
        self.MainCanvas.configure(highlightcolor="#000000")
        self.MainCanvas.configure(insertbackground="#000000")
        self.MainCanvas.configure(relief="ridge")
        self.MainCanvas.configure(selectbackground="#c4c4c4")
        self.MainCanvas.configure(selectforeground="black")

        self.LabelTextPath = tk.Label(self.MainFrame)
        self.LabelTextPath.place(relx=0.016, rely=0.924, height=20, width=115)
        self.LabelTextPath.configure(activebackground="#f9f9f9")
        self.LabelTextPath.configure(activeforeground="black")
        self.LabelTextPath.configure(anchor='w')
        self.LabelTextPath.configure(background="#d9d9d9")
        self.LabelTextPath.configure(compound='left')
        self.LabelTextPath.configure(disabledforeground="#a3a3a3")
        self.LabelTextPath.configure(foreground="#000000")
        self.LabelTextPath.configure(highlightbackground="#d9d9d9")
        self.LabelTextPath.configure(highlightcolor="#000000")
        self.LabelTextPath.configure(text='''File directory path:''')

        self.LabelDirectoryPathName = tk.Label(self.MainFrame)
        self.LabelDirectoryPathName.place(relx=0.016, rely=0.955, height=20
                , width=881)
        self.LabelDirectoryPathName.configure(activebackground="#f9f9f9")
        self.LabelDirectoryPathName.configure(activeforeground="black")
        self.LabelDirectoryPathName.configure(anchor='w')
        self.LabelDirectoryPathName.configure(background="#d9d9d9")
        self.LabelDirectoryPathName.configure(compound='left')
        self.LabelDirectoryPathName.configure(disabledforeground="#a3a3a3")
        self.LabelDirectoryPathName.configure(foreground="#000000")
        self.LabelDirectoryPathName.configure(highlightbackground="#d9d9d9")
        self.LabelDirectoryPathName.configure(highlightcolor="#000000")
        self.LabelDirectoryPathName.configure(text='''<vazio>''')

        # _style_code()
        self.TextBox_output = ScrolledText(self.MainFrame)
        self.TextBox_output.place(relx=0.638, rely=0.015, relheight=0.417
                , relwidth=0.355)
        self.TextBox_output.configure(background="white")
        self.TextBox_output.configure(font="-family {Courier New} -size 10")
        self.TextBox_output.configure(foreground="#000000")
        self.TextBox_output.configure(highlightbackground="#d9d9d9")
        self.TextBox_output.configure(highlightcolor="#000000")
        self.TextBox_output.configure(insertbackground="#000000")
        self.TextBox_output.configure(insertborderwidth="3")
        self.TextBox_output.configure(selectbackground="#c4c4c4")
        self.TextBox_output.configure(selectforeground="black")
        self.TextBox_output.configure(wrap="none")

        self.Label_coords = tk.Label(self.MainFrame)
        self.Label_coords.place(relx=0.54, rely=0.924, height=21, width=119)
        self.Label_coords.configure(activebackground="#f9f9f9")
        self.Label_coords.configure(activeforeground="black")
        self.Label_coords.configure(anchor='w')
        self.Label_coords.configure(background="#d9d9d9")
        self.Label_coords.configure(compound='left')
        self.Label_coords.configure(disabledforeground="#a3a3a3")
        self.Label_coords.configure(foreground="#000000")
        self.Label_coords.configure(highlightbackground="#d9d9d9")
        self.Label_coords.configure(highlightcolor="#000000")
        self.Label_coords.configure(text='''x: 123.22  |  y = 123.22''')

        self.CanvasHistogram = tk.Canvas(self.MainFrame)
        self.CanvasHistogram.place(relx=0.638, rely=0.439, relheight=0.474
                , relwidth=0.355)
        self.CanvasHistogram.configure(background="#d9d9d9")
        self.CanvasHistogram.configure(borderwidth="2")
        self.CanvasHistogram.configure(highlightbackground="#d9d9d9")
        self.CanvasHistogram.configure(highlightcolor="#000000")
        self.CanvasHistogram.configure(insertbackground="#000000")
        self.CanvasHistogram.configure(relief="ridge")
        self.CanvasHistogram.configure(selectbackground="#c4c4c4")
        self.CanvasHistogram.configure(selectforeground="black")

class TopLevel_SegmentationWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("517x225+731+26")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Segmentation settings")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.edge_detection_var = tk.StringVar()
        self.meanSTD_var = tk.StringVar()
        self.rb_filter = tk.IntVar()
        self.numberedgrains_var = tk.IntVar()
        self.minmax_var = tk.IntVar()
        self.boundarybox_var = tk.IntVar()
        self.colorfill_var = tk.IntVar()
        self.drawcnt_var = tk.IntVar()

        self.LabelFrame_Segmentation = tk.LabelFrame(self.top)
        self.LabelFrame_Segmentation.place(relx=0.019, rely=0.044
                , relheight=0.911, relwidth=0.967)
        self.LabelFrame_Segmentation.configure(relief='groove')
        self.LabelFrame_Segmentation.configure(foreground="#000000")
        self.LabelFrame_Segmentation.configure(text='''Segmentation''')
        self.LabelFrame_Segmentation.configure(background="#d9d9d9")
        self.LabelFrame_Segmentation.configure(highlightbackground="#d9d9d9")
        self.LabelFrame_Segmentation.configure(highlightcolor="#000000")

        self.lab47_lab47 = tk.LabelFrame(self.LabelFrame_Segmentation)
        self.lab47_lab47.place(relx=0.02, rely=0.098, relheight=0.854
                , relwidth=0.28, bordermode='ignore')
        self.lab47_lab47.configure(relief='groove')
        self.lab47_lab47.configure(foreground="#000000")
        self.lab47_lab47.configure(text='''Filters''')
        self.lab47_lab47.configure(background="#d9d9d9")
        self.lab47_lab47.configure(highlightbackground="#d9d9d9")
        self.lab47_lab47.configure(highlightcolor="#000000")

        self.RadioButton_Filter_None = tk.Radiobutton(self.lab47_lab47)
        self.RadioButton_Filter_None.place(relx=0.071, rely=0.114
                , relheight=0.143, relwidth=0.407, bordermode='ignore')
        self.RadioButton_Filter_None.configure(activebackground="beige")
        self.RadioButton_Filter_None.configure(activeforeground="black")
        self.RadioButton_Filter_None.configure(anchor='w')
        self.RadioButton_Filter_None.configure(background="#d9d9d9")
        self.RadioButton_Filter_None.configure(command=gui_main_2_support.select_filter)
        self.RadioButton_Filter_None.configure(compound='left')
        self.RadioButton_Filter_None.configure(disabledforeground="#a3a3a3")
        self.RadioButton_Filter_None.configure(foreground="#000000")
        self.RadioButton_Filter_None.configure(highlightbackground="#d9d9d9")
        self.RadioButton_Filter_None.configure(highlightcolor="#000000")
        self.RadioButton_Filter_None.configure(justify='left')
        self.RadioButton_Filter_None.configure(selectcolor="#d9d9d9")
        self.RadioButton_Filter_None.configure(text='''None''')
        self.RadioButton_Filter_None.configure(value='1')
        self.RadioButton_Filter_None.configure(variable=self.rb_filter)

        self.RadioButton_Filter_GaussianBlur = tk.Radiobutton(self.lab47_lab47)
        self.RadioButton_Filter_GaussianBlur.place(relx=0.071, rely=0.229
                , relheight=0.143, relwidth=0.707, bordermode='ignore')
        self.RadioButton_Filter_GaussianBlur.configure(activebackground="beige")
        self.RadioButton_Filter_GaussianBlur.configure(activeforeground="black")
        self.RadioButton_Filter_GaussianBlur.configure(anchor='w')
        self.RadioButton_Filter_GaussianBlur.configure(background="#d9d9d9")
        self.RadioButton_Filter_GaussianBlur.configure(command=gui_main_2_support.select_filter)
        self.RadioButton_Filter_GaussianBlur.configure(compound='left')
        self.RadioButton_Filter_GaussianBlur.configure(disabledforeground="#a3a3a3")
        self.RadioButton_Filter_GaussianBlur.configure(foreground="#000000")
        self.RadioButton_Filter_GaussianBlur.configure(highlightbackground="#d9d9d9")
        self.RadioButton_Filter_GaussianBlur.configure(highlightcolor="#000000")
        self.RadioButton_Filter_GaussianBlur.configure(justify='left')
        self.RadioButton_Filter_GaussianBlur.configure(selectcolor="#d9d9d9")
        self.RadioButton_Filter_GaussianBlur.configure(text='''Gaussian Blur''')
        self.RadioButton_Filter_GaussianBlur.configure(value='2')
        self.RadioButton_Filter_GaussianBlur.configure(variable=self.rb_filter)

        self.RadioButton_Filter_2DConvolution = tk.Radiobutton(self.lab47_lab47)
        self.RadioButton_Filter_2DConvolution.place(relx=0.071, rely=0.343
                , relheight=0.143, relwidth=0.793, bordermode='ignore')
        self.RadioButton_Filter_2DConvolution.configure(activebackground="beige")
        self.RadioButton_Filter_2DConvolution.configure(activeforeground="black")
        self.RadioButton_Filter_2DConvolution.configure(anchor='w')
        self.RadioButton_Filter_2DConvolution.configure(background="#d9d9d9")
        self.RadioButton_Filter_2DConvolution.configure(command=gui_main_2_support.select_filter)
        self.RadioButton_Filter_2DConvolution.configure(compound='left')
        self.RadioButton_Filter_2DConvolution.configure(disabledforeground="#a3a3a3")
        self.RadioButton_Filter_2DConvolution.configure(foreground="#000000")
        self.RadioButton_Filter_2DConvolution.configure(highlightbackground="#d9d9d9")
        self.RadioButton_Filter_2DConvolution.configure(highlightcolor="#000000")
        self.RadioButton_Filter_2DConvolution.configure(justify='left')
        self.RadioButton_Filter_2DConvolution.configure(selectcolor="#d9d9d9")
        self.RadioButton_Filter_2DConvolution.configure(text='''2D Convolution''')
        self.RadioButton_Filter_2DConvolution.configure(value='3')
        self.RadioButton_Filter_2DConvolution.configure(variable=self.rb_filter)

        self.Radiobutton_Filter_Bilateral = tk.Radiobutton(self.lab47_lab47)
        self.Radiobutton_Filter_Bilateral.place(relx=0.071, rely=0.457
                , relheight=0.143, relwidth=0.5, bordermode='ignore')
        self.Radiobutton_Filter_Bilateral.configure(activebackground="beige")
        self.Radiobutton_Filter_Bilateral.configure(activeforeground="black")
        self.Radiobutton_Filter_Bilateral.configure(anchor='w')
        self.Radiobutton_Filter_Bilateral.configure(background="#d9d9d9")
        self.Radiobutton_Filter_Bilateral.configure(command=gui_main_2_support.select_filter)
        self.Radiobutton_Filter_Bilateral.configure(compound='left')
        self.Radiobutton_Filter_Bilateral.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_Filter_Bilateral.configure(foreground="#000000")
        self.Radiobutton_Filter_Bilateral.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_Filter_Bilateral.configure(highlightcolor="#000000")
        self.Radiobutton_Filter_Bilateral.configure(justify='left')
        self.Radiobutton_Filter_Bilateral.configure(selectcolor="#d9d9d9")
        self.Radiobutton_Filter_Bilateral.configure(text='''Bilateral''')
        self.Radiobutton_Filter_Bilateral.configure(value='4')
        self.Radiobutton_Filter_Bilateral.configure(variable=self.rb_filter)

        self.Radiobutton_Filter_MedianBlur = tk.Radiobutton(self.lab47_lab47)
        self.Radiobutton_Filter_MedianBlur.place(relx=0.071, rely=0.571
                , relheight=0.143, relwidth=0.657, bordermode='ignore')
        self.Radiobutton_Filter_MedianBlur.configure(activebackground="beige")
        self.Radiobutton_Filter_MedianBlur.configure(activeforeground="black")
        self.Radiobutton_Filter_MedianBlur.configure(anchor='w')
        self.Radiobutton_Filter_MedianBlur.configure(background="#d9d9d9")
        self.Radiobutton_Filter_MedianBlur.configure(command=gui_main_2_support.select_filter)
        self.Radiobutton_Filter_MedianBlur.configure(compound='left')
        self.Radiobutton_Filter_MedianBlur.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_Filter_MedianBlur.configure(foreground="#000000")
        self.Radiobutton_Filter_MedianBlur.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_Filter_MedianBlur.configure(highlightcolor="#000000")
        self.Radiobutton_Filter_MedianBlur.configure(justify='left')
        self.Radiobutton_Filter_MedianBlur.configure(selectcolor="#d9d9d9")
        self.Radiobutton_Filter_MedianBlur.configure(text='''Median Blur''')
        self.Radiobutton_Filter_MedianBlur.configure(value='5')
        self.Radiobutton_Filter_MedianBlur.configure(variable=self.rb_filter)

        self.Radiobutton_Filter_Laplacian = tk.Radiobutton(self.lab47_lab47)
        self.Radiobutton_Filter_Laplacian.place(relx=0.071, rely=0.8
                , relheight=0.143, relwidth=0.436, bordermode='ignore')
        self.Radiobutton_Filter_Laplacian.configure(activebackground="beige")
        self.Radiobutton_Filter_Laplacian.configure(activeforeground="black")
        self.Radiobutton_Filter_Laplacian.configure(anchor='w')
        self.Radiobutton_Filter_Laplacian.configure(background="#d9d9d9")
        self.Radiobutton_Filter_Laplacian.configure(command=gui_main_2_support.select_filter)
        self.Radiobutton_Filter_Laplacian.configure(compound='left')
        self.Radiobutton_Filter_Laplacian.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_Filter_Laplacian.configure(foreground="#000000")
        self.Radiobutton_Filter_Laplacian.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_Filter_Laplacian.configure(highlightcolor="#000000")
        self.Radiobutton_Filter_Laplacian.configure(justify='left')
        self.Radiobutton_Filter_Laplacian.configure(selectcolor="#d9d9d9")
        self.Radiobutton_Filter_Laplacian.configure(text='''Binary''')
        self.Radiobutton_Filter_Laplacian.configure(value='7')
        self.Radiobutton_Filter_Laplacian.configure(variable=self.rb_filter)

        self.Radiobutton_Averaging = tk.Radiobutton(self.lab47_lab47)
        self.Radiobutton_Averaging.place(relx=0.071, rely=0.686, relheight=0.143
                , relwidth=0.586, bordermode='ignore')
        self.Radiobutton_Averaging.configure(activebackground="beige")
        self.Radiobutton_Averaging.configure(activeforeground="black")
        self.Radiobutton_Averaging.configure(anchor='w')
        self.Radiobutton_Averaging.configure(background="#d9d9d9")
        self.Radiobutton_Averaging.configure(command=gui_main_2_support.select_filter)
        self.Radiobutton_Averaging.configure(compound='left')
        self.Radiobutton_Averaging.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_Averaging.configure(foreground="#000000")
        self.Radiobutton_Averaging.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_Averaging.configure(highlightcolor="#000000")
        self.Radiobutton_Averaging.configure(justify='left')
        self.Radiobutton_Averaging.configure(selectcolor="#d9d9d9")
        self.Radiobutton_Averaging.configure(text='''Averaging''')
        self.Radiobutton_Averaging.configure(value='6')
        self.Radiobutton_Averaging.configure(variable=self.rb_filter)

        self.Labelframe_Edgedetection = tk.LabelFrame(self.LabelFrame_Segmentation)
        self.Labelframe_Edgedetection.place(relx=0.32, rely=0.098
                , relheight=0.268, relwidth=0.34, bordermode='ignore')
        self.Labelframe_Edgedetection.configure(relief='groove')
        self.Labelframe_Edgedetection.configure(foreground="#000000")
        self.Labelframe_Edgedetection.configure(text='''Edge detection method''')
        self.Labelframe_Edgedetection.configure(background="#d9d9d9")
        self.Labelframe_Edgedetection.configure(highlightbackground="#d9d9d9")
        self.Labelframe_Edgedetection.configure(highlightcolor="#000000")

        # _style_code()
        self.ComboBox_EdgeDetectionMethods = ttk.Combobox(self.Labelframe_Edgedetection)
        self.ComboBox_EdgeDetectionMethods.place(relx=0.059, rely=0.364
                , relheight=0.382, relwidth=0.824, bordermode='ignore')
        self.value_list = ['Canny','Sobel','Prewitt',]
        self.ComboBox_EdgeDetectionMethods.configure(values=self.value_list)
        self.ComboBox_EdgeDetectionMethods.configure(textvariable=self.edge_detection_var)
        self.ComboBox_EdgeDetectionMethods.configure(takefocus="")

        self.lab47_lab48 = tk.LabelFrame(self.LabelFrame_Segmentation)
        self.lab47_lab48.place(relx=0.32, rely=0.39, relheight=0.268
                , relwidth=0.34, bordermode='ignore')
        self.lab47_lab48.configure(relief='groove')
        self.lab47_lab48.configure(foreground="#000000")
        self.lab47_lab48.configure(text='''Mean and STD amplification''')
        self.lab47_lab48.configure(background="#d9d9d9")
        self.lab47_lab48.configure(highlightbackground="#d9d9d9")
        self.lab47_lab48.configure(highlightcolor="#000000")

        self.lab47_lab48_lab49 = tk.Label(self.lab47_lab48)
        self.lab47_lab48_lab49.place(relx=0.059, rely=0.545, height=21, width=6
                , bordermode='ignore')
        self.lab47_lab48_lab49.configure(activebackground="#f9f9f9")
        self.lab47_lab48_lab49.configure(activeforeground="black")
        self.lab47_lab48_lab49.configure(anchor='w')
        self.lab47_lab48_lab49.configure(background="#d9d9d9")
        self.lab47_lab48_lab49.configure(compound='left')
        self.lab47_lab48_lab49.configure(disabledforeground="#a3a3a3")
        self.lab47_lab48_lab49.configure(foreground="#000000")
        self.lab47_lab48_lab49.configure(highlightbackground="#d9d9d9")
        self.lab47_lab48_lab49.configure(highlightcolor="#000000")

        self.ComboBox_MeanSTD = ttk.Combobox(self.lab47_lab48)
        self.ComboBox_MeanSTD.place(relx=0.059, rely=0.364, relheight=0.382
                , relwidth=0.253, bordermode='ignore')
        self.value_list = ['1','2','3','4','5','6','7','8','9','10',]
        self.ComboBox_MeanSTD.configure(values=self.value_list)
        self.ComboBox_MeanSTD.configure(textvariable=self.meanSTD_var)
        self.ComboBox_MeanSTD.configure(takefocus="")

        self.lab47_lab49 = tk.LabelFrame(self.LabelFrame_Segmentation)
        self.lab47_lab49.place(relx=0.68, rely=0.098, relheight=0.805
                , relwidth=0.3, bordermode='ignore')
        self.lab47_lab49.configure(relief='groove')
        self.lab47_lab49.configure(foreground="#000000")
        self.lab47_lab49.configure(text='''Dsiplay options''')
        self.lab47_lab49.configure(background="#d9d9d9")
        self.lab47_lab49.configure(highlightbackground="#d9d9d9")
        self.lab47_lab49.configure(highlightcolor="#000000")

        self.CheckBox_NumberedGrains = ttk.Checkbutton(self.lab47_lab49)
        self.CheckBox_NumberedGrains.place(relx=0.067, rely=0.121, relwidth=0.72
                , relheight=0.0, height=19, bordermode='ignore')
        self.CheckBox_NumberedGrains.configure(variable=self.numberedgrains_var)
        self.CheckBox_NumberedGrains.configure(takefocus="")
        self.CheckBox_NumberedGrains.configure(text='''Numbered grains''')
        self.CheckBox_NumberedGrains.configure(compound='left')
        self.CheckBox_NumberedGrains_tooltip = \
        ToolTip(self.CheckBox_NumberedGrains, '''Each grain recives a tag number''')

        self.CheckBox_minmax = ttk.Checkbutton(self.lab47_lab49)
        self.CheckBox_minmax.place(relx=0.067, rely=0.242, relwidth=0.833
                , relheight=0.0, height=19, bordermode='ignore')
        self.CheckBox_minmax.configure(variable=self.minmax_var)
        self.CheckBox_minmax.configure(takefocus="")
        self.CheckBox_minmax.configure(text='''Hightlight min/max.''')
        self.CheckBox_minmax.configure(compound='left')
        self.CheckBox_minmax_tooltip = \
        ToolTip(self.CheckBox_minmax, '''Highlight the smallest and the largest grains.''')

        self.CheckBox_BoundaryBox = ttk.Checkbutton(self.lab47_lab49)
        self.CheckBox_BoundaryBox.place(relx=0.067, rely=0.364, relwidth=0.807
                , relheight=0.0, height=19, bordermode='ignore')
        self.CheckBox_BoundaryBox.configure(variable=self.boundarybox_var)
        self.CheckBox_BoundaryBox.configure(takefocus="")
        self.CheckBox_BoundaryBox.configure(text='''Grain boundary box''')
        self.CheckBox_BoundaryBox.configure(compound='left')
        self.CheckBox_BoundaryBox_tooltip = \
        ToolTip(self.CheckBox_BoundaryBox, '''Draw a boundary box around each grain.''')

        self.CheckBox_fill_grains = ttk.Checkbutton(self.lab47_lab49)
        self.CheckBox_fill_grains.place(relx=0.067, rely=0.485, relwidth=0.64
                , relheight=0.0, height=19, bordermode='ignore')
        self.CheckBox_fill_grains.configure(variable=self.colorfill_var)
        self.CheckBox_fill_grains.configure(takefocus="")
        self.CheckBox_fill_grains.configure(text='''Color fill grains''')
        self.CheckBox_fill_grains.configure(compound='left')
        self.CheckBox_fill_grains_tooltip = \
        ToolTip(self.CheckBox_fill_grains, '''Fill grains interior''')

        self.CheckBox = ttk.Checkbutton(self.lab47_lab49)
        self.CheckBox.place(relx=0.067, rely=0.606, relwidth=0.62, relheight=0.0
                , height=19, bordermode='ignore')
        self.CheckBox.configure(variable=self.drawcnt_var)
        self.CheckBox.configure(takefocus="")
        self.CheckBox.configure(text='''Draw contours''')
        self.CheckBox.configure(compound='left')

        self.ButtonDataImage = tk.Button(self.LabelFrame_Segmentation)
        self.ButtonDataImage.place(relx=0.32, rely=0.732, height=34, width=87
                , bordermode='ignore')
        self.ButtonDataImage.configure(activebackground="beige")
        self.ButtonDataImage.configure(activeforeground="black")
        self.ButtonDataImage.configure(background="#d9d9d9")
        self.ButtonDataImage.configure(command=gui_main_2_support.open_data_image_window)
        self.ButtonDataImage.configure(compound='left')
        self.ButtonDataImage.configure(disabledforeground="#a3a3a3")
        self.ButtonDataImage.configure(foreground="#000000")
        self.ButtonDataImage.configure(highlightbackground="#d9d9d9")
        self.ButtonDataImage.configure(highlightcolor="#000000")
        self.ButtonDataImage.configure(pady="0")
        self.ButtonDataImage.configure(text='''Data image''')
        self.ButtonDataImage_tooltip = \
        ToolTip(self.ButtonDataImage, '''Opens the data image window''')

        self.ButtonApplySgmentation = tk.Button(self.LabelFrame_Segmentation)
        self.ButtonApplySgmentation.place(relx=0.52, rely=0.732, height=34
                , width=67, bordermode='ignore')
        self.ButtonApplySgmentation.configure(activebackground="beige")
        self.ButtonApplySgmentation.configure(activeforeground="black")
        self.ButtonApplySgmentation.configure(background="#d9d9d9")
        self.ButtonApplySgmentation.configure(command=gui_main_2_support.start_grains_segmentation)
        self.ButtonApplySgmentation.configure(compound='left')
        self.ButtonApplySgmentation.configure(disabledforeground="#a3a3a3")
        self.ButtonApplySgmentation.configure(foreground="#000000")
        self.ButtonApplySgmentation.configure(highlightbackground="#d9d9d9")
        self.ButtonApplySgmentation.configure(highlightcolor="#000000")
        self.ButtonApplySgmentation.configure(pady="0")
        self.ButtonApplySgmentation.configure(text='''Apply''')

class ImageDataWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("329x92+886+380")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Image data")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.lab53 = tk.LabelFrame(self.top)
        self.lab53.place(relx=0.03, rely=0.109, relheight=0.815, relwidth=0.942)
        self.lab53.configure(relief='groove')
        self.lab53.configure(foreground="#000000")
        self.lab53.configure(background="#d9d9d9")
        self.lab53.configure(highlightbackground="#d9d9d9")
        self.lab53.configure(highlightcolor="#000000")

        self.LabelMagnification = tk.Label(self.lab53)
        self.LabelMagnification.place(relx=0.032, rely=0.133, height=21
                , width=147, bordermode='ignore')
        self.LabelMagnification.configure(activebackground="#f9f9f9")
        self.LabelMagnification.configure(activeforeground="black")
        self.LabelMagnification.configure(anchor='w')
        self.LabelMagnification.configure(background="#d9d9d9")
        self.LabelMagnification.configure(compound='left')
        self.LabelMagnification.configure(disabledforeground="#a3a3a3")
        self.LabelMagnification.configure(foreground="#000000")
        self.LabelMagnification.configure(highlightbackground="#d9d9d9")
        self.LabelMagnification.configure(highlightcolor="#000000")
        self.LabelMagnification.configure(text='''Magnification                    X''')

        self.LabelGetScale = tk.Label(self.lab53)
        self.LabelGetScale.place(relx=0.194, rely=0.533, height=21, width=116
                , bordermode='ignore')
        self.LabelGetScale.configure(activebackground="#f9f9f9")
        self.LabelGetScale.configure(activeforeground="black")
        self.LabelGetScale.configure(anchor='w')
        self.LabelGetScale.configure(background="#d9d9d9")
        self.LabelGetScale.configure(compound='left')
        self.LabelGetScale.configure(disabledforeground="#a3a3a3")
        self.LabelGetScale.configure(foreground="#000000")
        self.LabelGetScale.configure(highlightbackground="#d9d9d9")
        self.LabelGetScale.configure(highlightcolor="#000000")
        self.LabelGetScale.configure(text='''Scale                   (um)''')

        self.EntryMagnification = tk.Entry(self.lab53)
        self.EntryMagnification.place(relx=0.323, rely=0.133, height=20
                , relwidth=0.142, bordermode='ignore')
        self.EntryMagnification.configure(background="white")
        self.EntryMagnification.configure(disabledforeground="#a3a3a3")
        self.EntryMagnification.configure(font="TkFixedFont")
        self.EntryMagnification.configure(foreground="#000000")
        self.EntryMagnification.configure(highlightbackground="#d9d9d9")
        self.EntryMagnification.configure(highlightcolor="#000000")
        self.EntryMagnification.configure(insertbackground="#000000")
        self.EntryMagnification.configure(selectbackground="#c4c4c4")
        self.EntryMagnification.configure(selectforeground="black")

        self.EntryScale = tk.Entry(self.lab53)
        self.EntryScale.place(relx=0.323, rely=0.533, height=20, relwidth=0.142
                , bordermode='ignore')
        self.EntryScale.configure(background="white")
        self.EntryScale.configure(disabledforeground="#a3a3a3")
        self.EntryScale.configure(font="TkFixedFont")
        self.EntryScale.configure(foreground="#000000")
        self.EntryScale.configure(highlightbackground="#d9d9d9")
        self.EntryScale.configure(highlightcolor="#000000")
        self.EntryScale.configure(insertbackground="#000000")
        self.EntryScale.configure(selectbackground="#c4c4c4")
        self.EntryScale.configure(selectforeground="black")
        self.EntryScale_tooltip = \
        ToolTip(self.EntryScale, '''After drawing a straight line over the image, type the value presented on the image.''')

        self.ButtonDataImageClose = tk.Button(self.lab53)
        self.ButtonDataImageClose.place(relx=0.645, rely=0.267, height=34
                , width=77, bordermode='ignore')
        self.ButtonDataImageClose.configure(activebackground="beige")
        self.ButtonDataImageClose.configure(activeforeground="black")
        self.ButtonDataImageClose.configure(background="#d9d9d9")
        self.ButtonDataImageClose.configure(command=gui_main_2_support.conclude_data_image_collect)
        self.ButtonDataImageClose.configure(compound='left')
        self.ButtonDataImageClose.configure(disabledforeground="#a3a3a3")
        self.ButtonDataImageClose.configure(foreground="#000000")
        self.ButtonDataImageClose.configure(highlightbackground="#d9d9d9")
        self.ButtonDataImageClose.configure(highlightcolor="#000000")
        self.ButtonDataImageClose.configure(pady="0")
        self.ButtonDataImageClose.configure(text='''OK''')

class TopLevel_MeasuringProcedure:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("454x180+242+230")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Determining Average Grain Size - ASTM/E112-12")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.procedure_var = tk.StringVar()

        self.BUtton_ApplyProcudure = tk.Button(self.top)
        self.BUtton_ApplyProcudure.place(relx=0.639, rely=0.222, height=34
                , width=137)
        self.BUtton_ApplyProcudure.configure(activebackground="beige")
        self.BUtton_ApplyProcudure.configure(activeforeground="black")
        self.BUtton_ApplyProcudure.configure(background="#d9d9d9")
        self.BUtton_ApplyProcudure.configure(compound='left')
        self.BUtton_ApplyProcudure.configure(disabledforeground="#a3a3a3")
        self.BUtton_ApplyProcudure.configure(foreground="#000000")
        self.BUtton_ApplyProcudure.configure(highlightbackground="#d9d9d9")
        self.BUtton_ApplyProcudure.configure(highlightcolor="#000000")
        self.BUtton_ApplyProcudure.configure(pady="0")
        self.BUtton_ApplyProcudure.configure(text='''Apply''')

        self.LabelChooseProcedure = tk.Label(self.top)
        self.LabelChooseProcedure.place(relx=0.022, rely=0.056, height=21
                , width=103)
        self.LabelChooseProcedure.configure(activebackground="#f9f9f9")
        self.LabelChooseProcedure.configure(activeforeground="black")
        self.LabelChooseProcedure.configure(anchor='w')
        self.LabelChooseProcedure.configure(background="#d9d9d9")
        self.LabelChooseProcedure.configure(compound='left')
        self.LabelChooseProcedure.configure(disabledforeground="#a3a3a3")
        self.LabelChooseProcedure.configure(foreground="#000000")
        self.LabelChooseProcedure.configure(highlightbackground="#d9d9d9")
        self.LabelChooseProcedure.configure(highlightcolor="#000000")
        self.LabelChooseProcedure.configure(text='''Choose Procedure''')

        _style_code()
        self.tCo65 = ttk.Combobox(self.top)
        self.tCo65.place(relx=0.264, rely=0.056, relheight=0.117, relwidth=0.308)

        self.value_list = ['Jeffries','Heyn','Hilliard','Abram',]
        self.tCo65.configure(values=self.value_list)
        self.tCo65.configure(textvariable=self.procedure_var)
        self.tCo65.configure(takefocus="")

        self.fra66 = tk.Frame(self.top)
        self.fra66.place(relx=0.022, rely=0.222, relheight=0.75, relwidth=0.584)
        self.fra66.configure(relief='groove')
        self.fra66.configure(borderwidth="2")
        self.fra66.configure(relief="groove")
        self.fra66.configure(background="#d9d9d9")
        self.fra66.configure(highlightbackground="#d9d9d9")
        self.fra66.configure(highlightcolor="#000000")

        self.ButtonCloseProcedureWindow = tk.Button(self.top)
        self.ButtonCloseProcedureWindow.place(relx=0.639, rely=0.444, height=34
                , width=137)
        self.ButtonCloseProcedureWindow.configure(activebackground="beige")
        self.ButtonCloseProcedureWindow.configure(activeforeground="black")
        self.ButtonCloseProcedureWindow.configure(background="#d9d9d9")
        self.ButtonCloseProcedureWindow.configure(compound='left')
        self.ButtonCloseProcedureWindow.configure(disabledforeground="#a3a3a3")
        self.ButtonCloseProcedureWindow.configure(foreground="#000000")
        self.ButtonCloseProcedureWindow.configure(highlightbackground="#d9d9d9")
        self.ButtonCloseProcedureWindow.configure(highlightcolor="#000000")
        self.ButtonCloseProcedureWindow.configure(pady="0")
        self.ButtonCloseProcedureWindow.configure(text='''Button''')

from time import time, localtime, strftime
class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
                 follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
                   fg=_fgcolor, font="TkDefaultFont",
                   aspect=1000)
        self.msg.grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
    def configure(self, **kwargs):
        backgroundset = False
        foregroundset = False
        # Get the current tooltip text just in case the user doesn't provide any.
        current_text = self.msgVar.get()
        # to clear the tooltip text, use the .update method
        if 'debug' in kwargs.keys():
            debug = kwargs.pop('debug', False)
            if debug:
                for key, value in kwargs.items():
                    print(f'key: {key} - value: {value}')
        if 'background' in kwargs.keys():
            background = kwargs.pop('background')
            backgroundset = True
        if 'bg' in kwargs.keys():
            background = kwargs.pop('bg')
            backgroundset = True
        if 'foreground' in kwargs.keys():
            foreground = kwargs.pop('foreground')
            foregroundset = True
        if 'fg' in kwargs.keys():
            foreground = kwargs.pop('fg')
            foregroundset = True

        fontd = kwargs.pop('font', None)
        if 'text' in kwargs.keys():
            text = kwargs.pop('text')
            if (text == '') or (text == "\n"):
                text = current_text
            else:
                self.msgVar.set(text)
        reliefd = kwargs.pop('relief', 'flat')
        justifyd = kwargs.pop('justify', 'left')
        padxd = kwargs.pop('padx', 1)
        padyd = kwargs.pop('pady', 1)
        borderwidthd = kwargs.pop('borderwidth', 2)
        wid = self.msg      # The message widget which is the actual tooltip
        if backgroundset:
            wid.config(bg=background)
        if foregroundset:
            wid.config(fg=foreground)
        wid.config(font=fontd)
        wid.config(borderwidth=borderwidthd)
        wid.config(relief=reliefd)
        wid.config(justify=justifyd)
        wid.config(padx=padxd)
        wid.config(pady=padyd)
#                   End of Class ToolTip

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    gui_main_2_support.main()

if __name__ == '__main__':
    gui_main_2_support.main()




