#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Jun 02, 2020 06:00:00 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import threshold_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    threshold_gui_support.set_Tk_var()
    top = Toplevel1 (root)
    threshold_gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    threshold_gui_support.set_Tk_var()
    top = Toplevel1 (w)
    threshold_gui_support.init(root, w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("620x568+509+155")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Threshold Histogram")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Canvas = tk.Canvas(top)
        self.Canvas.place(relx=0.016, rely=0.018, relheight=0.704
                , relwidth=0.968)
        self.Canvas.configure(background="#d9d9d9")
        self.Canvas.configure(borderwidth="2")
        self.Canvas.configure(highlightbackground="#d9d9d9")
        self.Canvas.configure(highlightcolor="black")
        self.Canvas.configure(insertbackground="black")
        self.Canvas.configure(relief="ridge")
        self.Canvas.configure(selectbackground="#c4c4c4")
        self.Canvas.configure(selectforeground="black")

        self.Scale_Threshold = tk.Scale(top, from_=0, to=7)
        self.Scale_Threshold.place(relx=0.016, rely=0.739, relwidth=0.418
                , relheight=0.0, height=53, bordermode='ignore')
        self.Scale_Threshold.configure(activebackground="#ececec")
        self.Scale_Threshold.configure(background="#d9d9d9")
        self.Scale_Threshold.configure(command=threshold_gui_support.get_threshold)
        self.Scale_Threshold.configure(foreground="#000000")
        self.Scale_Threshold.configure(highlightbackground="#d9d9d9")
        self.Scale_Threshold.configure(highlightcolor="black")
        self.Scale_Threshold.configure(orient="horizontal")
        self.Scale_Threshold.configure(troughcolor="#d9d9d9")
        self.Scale_Threshold.configure(variable=threshold_gui_support.scalevar1)
        tooltip_font = "-family {Segoe UI} -size 9"
        ToolTip(self.Scale_Threshold, tooltip_font, '''Threshold value''', delay=0.5)

        self.Scale_Maxvalue = tk.Scale(top, from_=0.0, to=255.0)
        self.Scale_Maxvalue.place(relx=0.565, rely=0.739, relwidth=0.418
                , relheight=0.0, height=53, bordermode='ignore')
        self.Scale_Maxvalue.configure(activebackground="#ececec")
        self.Scale_Maxvalue.configure(background="#d9d9d9")
        self.Scale_Maxvalue.configure(command=threshold_gui_support.get_maxval)
        self.Scale_Maxvalue.configure(foreground="#000000")
        self.Scale_Maxvalue.configure(highlightbackground="#d9d9d9")
        self.Scale_Maxvalue.configure(highlightcolor="black")
        self.Scale_Maxvalue.configure(orient="horizontal")
        self.Scale_Maxvalue.configure(troughcolor="#d9d9d9")
        self.Scale_Maxvalue.configure(variable=threshold_gui_support.scalevar2)
        tooltip_font = "-family {Segoe UI} -size 9"
        ToolTip(self.Scale_Maxvalue, tooltip_font, '''    maximum value''', delay=0.5)

        self.Button = tk.Button(top)
        self.Button.place(relx=0.452, rely=0.863, height=24, width=77)
        self.Button.configure(activebackground="#ececec")
        self.Button.configure(activeforeground="#000000")
        self.Button.configure(background="#d9d9d9")
        self.Button.configure(command=threshold_gui_support.stop_process)
        self.Button.configure(disabledforeground="#a3a3a3")
        self.Button.configure(foreground="#000000")
        self.Button.configure(highlightbackground="#d9d9d9")
        self.Button.configure(highlightcolor="black")
        self.Button.configure(pady="0")
        self.Button.configure(text='''OK''')

# ======================================================
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=1, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in miliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

if __name__ == '__main__':
    vp_start_gui()





