#############################################################################
# Generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#  Jun 02, 2020 06:00:00 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 620x568+509+155
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Threshold Histogram"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can44 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 313 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 563 
    vTcl:DefineAlias "$top.can44" "Canvas" vTcl:WidgetProc "Toplevel1" 1
    scale $top.sca45 \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -command get_threshold -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -length 100 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 255.0 -troughcolor #d9d9d9 -variable scalevar1 
    vTcl:DefineAlias "$top.sca45" "Scale_Threshold" vTcl:WidgetProc "Toplevel1" 1
    bind $top.sca45 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Threshold value}
    }
    scale $top.sca46 \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -command get_maxval -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -length 100 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 255.0 -troughcolor #d9d9d9 -variable scalevar2 
    vTcl:DefineAlias "$top.sca46" "Scale_Maxvalue" vTcl:WidgetProc "Toplevel1" 1
    bind $top.sca46 <<SetBalloon>> {
        set ::vTcl::balloon::%W {	maximum value}
    }
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command destroy_window \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text OK 
    vTcl:DefineAlias "$top.but48" "Button" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can44 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.018 -width 0 -relwidth 0.968 \
        -height 0 -relheight 0.704 -anchor nw -bordermode ignore 
    place $top.sca45 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.739 -width 0 -relwidth 0.418 \
        -height 0 -relheight 0.093 -anchor nw -bordermode ignore 
    place $top.sca46 \
        -in $top -x 0 -relx 0.565 -y 0 -rely 0.739 -width 0 -relwidth 0.418 \
        -height 0 -relheight 0.093 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.452 -y 0 -rely 0.863 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}
proc get_threshold {args} { }
proc get_maxval {args} { }

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

